revisite UI Design
NicoSteinmueller/hwr-zeiterfassung-desktopfrontend pull request #3
Opened 2022-03-24 22:26 UTC by TomxHWRxWI20C

UI Design ist für den MVP soweit fertig

2022-03-25 16:48 UTC, valientes approved these changes
Should be fine since the dependencies are now part of the pull. Looks fancy.

2022-03-27 18:16 UTC, Stier-09 requested changes

2022-03-27 18:16 UTC, NicoSteinmueller commented on src/main/java/com/zeiterfassung/hwr/desktop/entities/Time.java
> +}
sollte im client nicht benötigt werden

2022-03-27 18:16 UTC, Stier-09 commented on src/main/java/com/zeiterfassung/hwr/desktop/entities/Human.java
> +    private String lastName;
wird das wirklich benötigt?

2022-03-28 08:08 UTC, TomxHWRxWI20C commented on src/main/java/com/zeiterfassung/hwr/desktop/entities/Human.java
> +    private String lastName;
Hast mal den Client auf deinem System ausgeführt?

2022-03-28 08:09 UTC, TomxHWRxWI20C commented on src/main/java/com/zeiterfassung/hwr/desktop/entities/Time.java
> +}
Woher bekommst du dann diese Infos, wenn nicht vom Client?

2022-03-28 10:08 UTC, Stier-09 approved these changes

2022-03-28 10:38 UTC, merged